// FETCHING ALL user

export const FETCHING_USERS_BY_ADMIN_REQUEST = 'FETCHING_USERS_BY_ADMIN_REQUEST'
export const FETCHING_USERS_BY_ADMIN_SUCCESS = 'FETCHING_USERS_BY_ADMIN_SUCCESS'
export const FETCHING_USERS_BY_ADMIN_FAIL = 'FETCHING_USERS_BY_ADMIN_FAIL'

// Edit or update USER
export const UPDATE_USER_BY_ADMIN_REQUEST = 'UPDATE_USER_BY_ADMIN_REQUEST'
export const UPDATE_USER_BY_ADMIN_SUCCESS = 'UPDATE_USER_BY_ADMIN_SUCCESS'
export const UPDATE_USER_BY_ADMIN_FAIL = 'UPDATE_USER_BY_ADMIN_FAIL'
export const UPDATE_USER_BY_ADMIN_RESET = 'UPDATE_USER_BY_ADMIN_RESET'

// Get user by admin
export const GET_USER_BY_ADMIN_REQUEST = 'GET_USER_BY_ADMIN_REQUEST'
export const GET_USER_BY_ADMIN_SUCCESS = 'GET_USER_BY_ADMIN_SUCCESS'
export const GET_USER_BY_ADMIN_FAIL = 'GET_USER_BY_ADMIN_FAIL'

// DELETE user by admin
export const DELETE_USER_BY_ADMIN_REQUEST = 'DELETE_USER_BY_ADMIN_REQUEST'
export const DELETE_USER_BY_ADMIN_SUCCESS = 'DELETE_USER_BY_ADMIN_SUCCESS'
export const DELETE_USER_BY_ADMIN_FAIL = 'DELETE_USER_BY_ADMIN_FAIL'
export const DELETE_USER_BY_ADMIN_RESET = 'DELETE_USER_BY_ADMIN_RESET'
